trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TOMCAT_WEBAPPS_DIR: '/opt/tomcat/webapps'

stages:
- stage: BuildWithMaven
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Building the application with Maven..."
        mvn clean package
      displayName: 'Build with Maven'

- stage: Deploy
  jobs:
  - job: DeployApplication
    steps:
    - script: |
        echo "Deploying the application to Tomcat server..."
        sudo cp target/java-tomcat-maven-example.war ${TOMCAT_WEBAPPS_DIR}/
      displayName: 'Deploy Application'

- stage: PostCleanup
  jobs:
  - job: CleanupWorkspace
    steps:
    - script: |
        echo "Cleaning up workspace..."
        rm -rf $(Agent.BuildDirectory)
      displayName: 'Clean Workspace'
